version: '3.3'

services:
  dots-game:
    image: cimlah/dots-game:latest
    restart: unless-stopped
    hostname: dots-game1
    container_name: dots-game1
    command: bash -c 'web/Docker/app-start.sh'
    volumes:
      - ../../.:/usr/src/app
    
    ports:
      - "5001:5001"
    tty: true
    networks:
      dots-game_network:
        ipv4_address: 172.21.1.2


networks:
  dots-game_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.21.1.0/24"