version: '3.3'

services:
  dots-game:
    image: cimlah/dots-game:backend-test
    restart: unless-stopped
    hostname: dots-game_backend-test
    container_name: dots-game_backend-test
    volumes:
      - ../../.:/usr/src/app
    command: bash -c 'web/Docker/app-start.sh'
    ports:
      - "3000:3000"
      - "5000:5000"
    tty: true
    networks:
      dots-game_network:
        ipv4_address: 172.21.1.2


networks:
  dots-game_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.21.1.0/24"