version: '3.3'

services:
  dots-game:
    image: cimlah/dots-game
    restart: unless-stopped
    hostname: dots-game1
    container_name: dots-game1
    ports:
      - "3000:3000"
    tty: true
    networks:
      dots-game_network:
        ipv4_address: 172.21.1.2


networks:
  dots-game_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.21.1.0/24"